### PR TITLE
Fixing ansible failure on quotation

### PR DESCRIPTION
**Pull request by radoslawc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Ansible in bootstrap-integration failing on kernel version check:
```
FAILED! => {"msg": "The conditional check 'ansible_facts.kernel == \"5.0.0-23-generic\" or True' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."}
```
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
It's passing [all the assertions](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/278/bootstrap-integration/1805637526392672256#1:build-log.txt%3A598)

/lgtm

**Comment by radoslawc** [comment]
Bootstrap integration worked, closing and change will go to 272 for clarity

**Pull request closed without merging**
