### PR TITLE
Small improvements on e2e scripts

### PR DESCRIPTION
**Pull request by electrocucaracha**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
The OAI containerlab network name doesn't match with the name used by free5gc. This could result in connectivity issues. As improvement, it was included a waiting process for Network instance resources.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
[Flakiness 009.sh test](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/223/e2e-free5gc-ubuntu-focal/1734983574924300288#1:build-log.txt%3A71132)

/override e2e-free5gc-ubuntu-focal

**Review by efiacor — APPROVED** [review]

**Pull request merged**
