### PR TITLE
updates README to reflect the correct file extension for 003-network-topo

### PR DESCRIPTION
**Pull request by vjayaramrh**

### CODE REVIEW

**Comment by vjayaramrh** [comment]
@henderiw FYI

**Comment by electrocucaracha** [comment]
@vjayaramrh I'm wondering why that extension was used? Shouldn't it be better to rename the file?

**Comment by electrocucaracha** [comment]
> @vjayaramrh I'm wondering why that extension was used? Shouldn't it be better to rename the file?

I think that the documentation is not reflecting what the [test is doing](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/003.sh#L39-L41), so it requires better explanation.

**Comment by vjayaramrh** [comment]
> 



> I think the user will need to do this, won't they (from the 003.sh script)?
> 
> ```
> export LEAF_IP=$(docker inspect net-free5gc-net-leaf -f '{{.NetworkSettings.Networks.kind.IPAddress}}')
> 
> envsubst <"$TESTDIR/003-network-topo.tmpl" >"$TESTDIR/003-network-topo.yaml"
> ```

@johnbelamaric I dont see a reference to execution of 0003.sh at the link https://github.com/nephio-project/test-infra/blob/main/e2e/provision/README.md

**Comment by vjayaramrh** [comment]
> The 001.sh, etc. all just are for the automated e2e tests. They do the various steps in the README in an automated way, so that we can (eventually) use them in e2e. We don't have the user execute them explicitly, though you could, instead of the steps in the README. But we want the user to do the steps to help them learn and understand what is going on. We share the .yaml files between the test scripts and the user so that the user doesn't have to copy every YAML over.
> 
> I would actually suggest we take this little snippet that generates the .yaml from the .tmpl, and we put it in the "hacks" directory, like we did with vlan-interfaces.sh, and just have the user call it from there. It will go away in R2 (or maybe R1++?).

Sounds good

**Comment by electrocucaracha** [comment]
@vjayaramrh I think the missing part here is to consume that hack from the test, take a look of how the [VLAN interfaces are created](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/002.sh#L55-L56)

@johnbelamaric maybe the [clab portion](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/002.sh#L46-L53) can be moved into a hack as well

**Comment by johnbelamaric** [comment]
Nice, thanks.

/approve
/lgtm

**Comment by johnbelamaric** [comment]
> @vjayaramrh I think the missing part here is to consume that hack from the test, take a look of how the [VLAN interfaces are created](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/002.sh#L55-L56)

yes, good point, we should add that
 
> @johnbelamaric maybe the [clab portion](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/002.sh#L46-L53) can be moved into a hack as well

Yes, we should do that as well

**Pull request merged**
