### PR TITLE
Enable Fedora 34 in Vagrantfile

### PR DESCRIPTION
**Pull request by electrocucaracha**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
Fedora 34 has been recently included as part of the CI process, this addition demonstrates its stability, providing an interesting alternative. This change offers the option to deploy Vagrant instances using Fedora 34 box. This also improves the CI process, reducing the number of packages to update.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The `OS_DISTRO` env variable defines the distro used for Vagrant. It's possible to provision a local VM with VirtualBox/Libvirt provider (`OS_DISTRO=fedora_34 vagrant up`) or a remote VM with GCP(`OS_DISTRO=fedora_34 GOOGLE_PROJECT_ID=pure-faculty-367518 GOOGLE_JSON_KEY_LOCATION=~/.config/gcloud/pure-faculty-367518-f1afca4feb6b.json NEPHIO_USER=$USER RUN_E2E=true vagrant up --provider google`)

**Does this PR introduce a user-facing change?**:

```release-note
Enable Fedora 34 Vagrant box
```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@vjayaramrh did you have a chance to take a look this change?

**Comment by vjayaramrh** [comment]
> @vjayaramrh did you have a chance to take a look this change?

@electrocucaracha Apologies, I was on PTO starting August 31st afternoon, Will take a look today.

**Review by vjayaramrh — APPROVED** [review]
/lgtm
However, I have not been able to test it out yet on my local dev box or gcp. Will test out once the PR is merged.

**Pull request merged**
