### PR TITLE
Add regional label

### PR DESCRIPTION
**Pull request by johnbelamaric**
This adds a regional label to the regional cluster.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@vjayaramrh @henderiw @rravindran123 @debeaueric 

Curious to hear your thoughts on this. Since there is only one regional cluster, this is not strictly necessary. In the AMF and SMF deployment steps, I currently use a PackageVariant - single clone operation to a single regional repo - instead of a PackageVariantSet. The main reason for that is that I had not labeled the regional cluster, because it's a little bit of a pain to do via the CLI.

Still, maybe it's worth doing - it shows how to edit the package via CLI. So, in this e2e README, we basically have you trying out the CLI, the UI, and using the PackageVariant/PackageVariantSet mechanism to modify a package.

WDYT? Is this more work and more confusing, or is it helpful to show?

**Comment by debeaueric** [comment]
I agree that we should label the Regional cluster. In more complex configuration, we may have various Regional clusters.
For the Readme for R1 Installation, I am not sure that we must explain different possibilities to add a label in Package. We should focus on explaining  the scripts used. We .should explain other possibilities in a separate document to avoid confusion.

**Comment by rravindran123** [comment]
I feel the same as Eric, good to keep the Cluster CRDs consistent and contextualized, so adding the label makes sense. Also shows enforces Nephio Day/0 of managing an hierarchical cloud deployment, where the control functions can be aggregated, spread or replicated  considering more complex scenarios  Network Slicing.

**Pull request merged**
