### PR TITLE
Dependabot config generator

### PR DESCRIPTION
**Pull request by radoslawc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature
> /kind flake

**What this PR does / why we need it**:
Dependabot has static configuration that doesn't allow to use globing/regexp etc. so with monorepos it has to be regenerated to reflect codebase changes.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@radoslawc correct me if I'm wrong, but the problem happens when someone adds files in the repository that were not initially conceived, so those files are not going to be part of the dependabot's scope, right? Like new Dokerfiles. If that's correct, I'm okay with this approach, but I think that it requires a scheduler job that executes this python script in regular basis, maybe a scheduled GitHub action.

Last but not least, don't forget to include license headers in the python script as well as the depedabot.yaml file generated.

**Comment by radoslawc** [comment]
> @radoslawc correct me if I'm wrong, but the problem happens when someone adds files in the repository that were not initially conceived, so those files are not going to be part of the dependabot's scope, right? Like new Dokerfiles. If that's correct,
Thats right, add or remove. 
> I'm okay with this approach, but I think that it requires a scheduler job that executes this python script in regular basis, maybe a scheduled GitHub action.
This will be ran with github action in every PR and pull this file from test-infra.
> Last but not least, don't forget to include license headers in the python script as well as the depedabot.yaml file generated.
Forgot about that, I'll add that shortly.

**Comment by electrocucaracha** [comment]
> > I'm okay with this approach, but I think that it requires a scheduler job that executes this python script in regular basis, maybe a scheduled GitHub action.
> 
> This will be ran with github action in every PR and pull this file from test-infra.

Another approach could be to add a Schedule GitHub job (creating the `.github/workflows/update.yml` file) that runs the script

```yaml
name: Scheduled GitHub action
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  updates-dependabot-content:
    permissions:
      contents: write  # for technote-space/create-pr-action to push code
      pull-requests: write  # for technote-space/create-pr-action to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: technote-space/create-pr-action@v2.1.4
        with:
          EXECUTE_COMMANDS: |
            python ./tools/dependabot/generate_dependabot.py
          COMMIT_MESSAGE: 'Upgrade dependabot content'
          COMMIT_NAME: 'nephio bot'
          PR_BRANCH_NAME: "dependabot-update-${PR_ID}"
          PR_TITLE: 'chore: update dependabot content'
```

**Comment by radoslawc** [comment]
> Another approach could be to add a Schedule GitHub job (creating the `.github/workflows/update.yml` file) that runs the script

I thought about running it on schedule, but eventually 'on push' so after PR gets merged looks like best idea. With amount of PRs we're getting it will not waste too much resources on runs without changes.

**Comment by electrocucaracha** [comment]
> I thought about running it on schedule, but eventually 'on push' so after PR gets merged looks like best idea. With amount of PRs we're getting it will not waste too much resources on runs without changes.

Ok, that makes sense. The only missing part is the prow changes to trigger the script execution.

/lgtm

**Pull request merged**
