### PR TITLE
Make ansible task names more descriptive 

### PR DESCRIPTION
**Pull request by kispaljr**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Makes some ansible task names more descriptive to make it easier to follow the progress of the install process.
This is especially useful for troubleshooting.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
Thanks @kispaljr for open this PR, I'll need to add some documentation to how to contribute to this project, but in the meantime I'll put some info here.

There is [tox environment](https://tox.wiki/en/4.11.3/#) for checking Ansible linting issues, you have to run `tox` from the `e2e/provision` folder. These are some of the issues reported tool with your changes

```console
name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/bootstrap/tasks/wait-deployments.yml:11 Task/Handler: Get deployment resources in '{{ namespace }}' namespace

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/bootstrap/tasks/wait-deployments.yml:19 Task/Handler: Print deployment resources in '{{ namespace }}' namespace

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/bootstrap/tasks/wait-deployments.yml:23 Task/Handler: Wait for deployments in '{{ namespace }}' namespace

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/install/tasks/wait_deployments.yml:11 Task/Handler: Get deployment resources in '{{ namespace }}' namespace

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/install/tasks/wait_deployments.yml:19 Task/Handler: Print deployment resources in '{{ namespace }}' namespace

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/install/tasks/wait_deployments.yml:23 Task/Handler: Wait for deployments in '{{ namespace }}' namespace

jinja[spacing]: Jinja2 spacing could be improved: Get '{{pkg}}' package content information -> Get '{{ pkg }}' package content information
playbooks/roles/kpt/tasks/main.yml:30 Jinja2 template rewrite recommendation: `Get '{{ pkg }}' package content information`.

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/kpt/tasks/main.yml:30 Task/Handler: Get '{{pkg}}' package content information

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/kpt/tasks/main.yml:36 Task/Handler: Print '{{ pkg }}' package content information

jinja[spacing]: Jinja2 spacing could be improved: Get '{{pkg}}' package differences between local and upstream -> Get '{{ pkg }}' package differences between local and upstream
playbooks/roles/kpt/tasks/main.yml:55 Jinja2 template rewrite recommendation: `Get '{{ pkg }}' package differences between local and upstream`.

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/kpt/tasks/main.yml:55 Task/Handler: Get '{{pkg}}' package differences between local and upstream

jinja[spacing]: Jinja2 spacing could be improved: Print '{{pkg}}' package initialization -> Print '{{ pkg }}' package initialization
playbooks/roles/kpt/tasks/main.yml:80 Jinja2 template rewrite recommendation: `Print '{{ pkg }}' package initialization`.

name[template]: Jinja templates should only be at the end of 'name'
playbooks/roles/kpt/tasks/main.yml:80 Task/Handler: Print '{{pkg}}' package initialization

Read documentation for instructions on how to ignore specific rule violations.

                     Rule Violation Summary
 count tag                   profile  rule associated tags
     3 jinja[spacing]        basic    formatting
     1 yaml[comments]        basic    formatting, yaml (warning)
     3 yaml[line-length]     basic    formatting, yaml (warning)
     1 yaml[trailing-spaces] basic    formatting, yaml (warning)
    10 name[template]        moderate idiom

Failed: 13 failure(s), 5 warning(s) on 72 files. Last profile that met the validation criteria was 'min'.
```

Can you make the proper changes to make sure it passes?

**Comment by kispaljr** [comment]
Sure, I did.
However, after fixing linter issues in the files I modified, `tox` still warns about some issues that wasn't introduced by this change. I guess that's still OK:
```
yaml[comments]: Missing starting space in comment (warning)
nephio.yaml:18

yaml[trailing-spaces]: Trailing spaces (warning)
nephio.yaml:20

yaml[line-length]: Line too long (166 > 160 characters) (warning)
nephio.yaml:31

yaml[line-length]: Line too long (180 > 160 characters) (warning)
playbooks/cluster.yml:75

yaml[line-length]: Line too long (181 > 160 characters) (warning)
playbooks/cluster.yml:79

Read documentation for instructions on how to ignore specific rule violations.

                     Rule Violation Summary
 count tag                   profile rule associated tags
     1 yaml[comments]        basic   formatting, yaml (warning)
     3 yaml[line-length]     basic   formatting, yaml (warning)
     1 yaml[trailing-spaces] basic   formatting, yaml (warning)

Passed: 0 failure(s), 5 warning(s) on 65 files. Last profile that met the validation criteria was 'min'.
```

**Comment by electrocucaracha** [comment]
> Sure, I did. However, after fixing linter issues in the files I modified, `tox` still warns about some issues that wasn't introduced by this change. I guess that's still OK:
> 
> ```
> yaml[comments]: Missing starting space in comment (warning)
> nephio.yaml:18
> 
> yaml[trailing-spaces]: Trailing spaces (warning)
> nephio.yaml:20
> 
> yaml[line-length]: Line too long (166 > 160 characters) (warning)
> nephio.yaml:31
> 
> yaml[line-length]: Line too long (180 > 160 characters) (warning)
> playbooks/cluster.yml:75
> 
> yaml[line-length]: Line too long (181 > 160 characters) (warning)
> playbooks/cluster.yml:79
> 
> Read documentation for instructions on how to ignore specific rule violations.
> 
>                      Rule Violation Summary
>  count tag                   profile rule associated tags
>      1 yaml[comments]        basic   formatting, yaml (warning)
>      3 yaml[line-length]     basic   formatting, yaml (warning)
>      1 yaml[trailing-spaces] basic   formatting, yaml (warning)
> 
> Passed: 0 failure(s), 5 warning(s) on 65 files. Last profile that met the validation criteria was 'min'.
> ```

`nephio.yaml` will be removed once we fully deprecated the [one summit repo](https://github.com/nephio-project/one-summit-22-workshop/), the `cluster.yml` issues can be fixed adjusting the lenght

/lgtm

**Comment by electrocucaracha** [comment]
@johnbelamaric I think that Porch is [still having issues](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/185/e2e-fedora-34/1701645951199875072#1:build-log.txt%3A61771) to manage some [Package Variant resources.](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/006.sh#L40)

**Pull request merged**
