### PR TITLE
Adding ansible galaxy install pre_task to deploy_kubeadm_k8s

### PR DESCRIPTION
**Pull request by dkosteck**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Previously there was a potential condition where the galaxy requirements were not satisfied before running the deploy_kubeadm_k8s.yml script. The install would only happen during init.sh.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dkosteck** [comment]
Tested on a fresh Fedora VM with and without change, validating that galaxy requirements are satisfied after the change

**Comment by electrocucaracha** [comment]
@dkosteck [it seems](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/308/e2e-kubeadm-ubuntu-jammy/1839740948670582784#1:build-log.txt%3A1649) that you have to use another path

**Comment by dkosteck** [comment]
> @dkosteck [it seems](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/308/e2e-kubeadm-ubuntu-jammy/1839740948670582784#1:build-log.txt%3A1649) that you have to use another path

@electrocucaracha Good catch, this was something I was considering when I was making this change and was wondering if there was a better way to do this than the relative parent directory. I'll poke around to see how to do this and make this change early next week

**Comment by vjayaramrh** [comment]
@efiacor Looks like 009.sh is failing as per the discussion yesterday on this PR for free5gc on ubuntu

**Pull request merged**
