### PR TITLE
Remove ones-22 config

### PR DESCRIPTION
**Pull request by efiacor**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Removal/cleanup of old ONES-2022 config and test

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@efiacor it seems like there are some leftovers in the terraform scripts
* https://github.com/nephio-project/test-infra/blob/main/e2e/terraform/modules/gcp/main.tf#L25
* https://github.com/nephio-project/test-infra/blob/main/e2e/terraform/modules/gcp/main.tf#L81-L91

**Comment by efiacor** [comment]
> @efiacor it seems like there are some leftovers in the terraform scripts
> 
>     * https://github.com/nephio-project/test-infra/blob/main/e2e/terraform/modules/gcp/main.tf#L25
> 
>     * https://github.com/nephio-project/test-infra/blob/main/e2e/terraform/modules/gcp/main.tf#L81-L91

I was unsure how to handle those tbh. Can we just remove them? Will it break anything with the terraform setup?

**Comment by electrocucaracha** [comment]
[Failed on flaky 009.sh test](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/246/e2e-free5gc-ubuntu-focal/1757074781234008064#1:build-log.txt%3A78305)

/override e2e-free5gc-ubuntu-focal
/lgtm
/approve

**Pull request merged**
