### PR TITLE
Switching e2e tests to run on main

### PR DESCRIPTION
**Pull request by radoslawc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation

/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Switching to main catalog branch
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liamfallon** [comment]
I found only two more references to v2.0.0 in the end to end tests:

https://github.com/nephio-project/test-infra/blob/8d9d67dfe172c50b92ae2e1642d640a98ec5909e/e2e/defaults.env#L14
The variable "REVISION" is used in a few places:
- https://github.com/nephio-project/test-infra/blob/8d9d67dfe172c50b92ae2e1642d640a98ec5909e/e2e/tests/free5gc/001.sh#L48
- https://github.com/nephio-project/test-infra/blob/8d9d67dfe172c50b92ae2e1642d640a98ec5909e/e2e/tests/free5gc/003.sh#L36
- https://github.com/nephio-project/test-infra/blob/8d9d67dfe172c50b92ae2e1642d640a98ec5909e/e2e/tests/oai/001b-infra-metal-lb.sh#L46

Then it looks like we are using a prebuilt version of the v2.0.0 `porchctl` command here:
https://github.com/nephio-project/test-infra/blob/8d9d67dfe172c50b92ae2e1642d640a98ec5909e/e2e/provision/playbooks/cluster.yml#L133

I think that frr `porchctl` we probably should build it from source in the e2e tests to make sure we have the latest version. There are some small changes in `porchctl` between R2 and R3

**Comment by electrocucaracha** [comment]
@radoslawc It seems like you missed the change on the [porch client version](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/cluster.yml#L133). BTW, I suggest completing [this issue](https://github.com/nephio-project/nephio/issues/593) in this release

**Review by liamfallon — COMMENTED** [review]
This is great!

**Comment by electrocucaracha** [comment]
@radoslawc @vjayaramrh @liamfallon [there is an error](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/272/bootstrap-integration/1805611760242135040#1:build-log.txt%3A596) on the bootstrap integration test that needs to be fixed. Please take time to review it.

```console
 TASK [bootstrap : Ensure gtp5g kernel constraints] *****************************
fatal: [int-focal-vm-bootstrap-3299538048]: FAILED! => {"msg": "The conditional check 'ansible_facts.kernel == \"5.0.0-23-generic\" or True' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."} 
```

**Comment by liamfallon** [comment]
> @radoslawc @vjayaramrh @liamfallon [there is an error](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/272/bootstrap-integration/1805611760242135040#1:build-log.txt%3A596) on the bootstrap integration test that needs to be fixed. Please take time to review it.
> 
> ```
>  TASK [bootstrap : Ensure gtp5g kernel constraints] *****************************
> fatal: [int-focal-vm-bootstrap-3299538048]: FAILED! => {"msg": "The conditional check 'ansible_facts.kernel == \"5.0.0-23-generic\" or True' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."} 
> ```

Thanks @electrocucaracha , we'll check it.

**Comment by radoslawc** [comment]
@electrocucaracha @liamfallon now bootstrap-integration fails on:
```
TASK [Gathering Facts] *********************************************************
fatal: [int-focal-vm-bootstrap-659977273]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@34.170.197.210: Permission denied (publickey).", "unreachable": true}
```
Only change was removing curly braces like in https://github.com/nephio-project/test-infra/pull/278/files where it worked afterwards.

**Comment by electrocucaracha** [comment]
> @electrocucaracha @liamfallon now bootstrap-integration fails on:
> 
> ```
> TASK [Gathering Facts] *********************************************************
> fatal: [int-focal-vm-bootstrap-659977273]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@34.170.197.210: Permission denied (publickey).", "unreachable": true}
> ```
> 
> Only change was removing curly braces like in https://github.com/nephio-project/test-infra/pull/278/files where it worked afterwards.

There is a tech debt on the integration tests, I'm not sure if it's conflicting with other existing VMs or sometimes GCP can't smoothly create those molecule instances. Usually those errors are gone in the second try, but definitely it's necessary to investigate the root cause

/test bootstrap-integration

**Comment by electrocucaracha** [comment]
@radoslawc @liamfallon @vjayaramrh be cautious to use retest prow commands, every error is an opportunity to improve the resiliency of the CI. Forcing some jobs can lead to future problems.

**Comment by liamfallon** [comment]
> @radoslawc @liamfallon @vjayaramrh be cautious to use retest prow commands, every error is an opportunity to improve the resiliency of the CI. Forcing some jobs can lead to future problems.

I opened this discussion:
https://github.com/nephio-project/nephio/discussions/774

**Pull request merged**
