### PR TITLE
Use workload cluster packages that avoid package context manipulation

### PR DESCRIPTION
**Pull request by johnbelamaric**
This reduced the flakiness of the cluster creation and package approval process.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
/hold

Wait until https://github.com/nephio-project/nephio-example-packages/pull/42 merges and we tag that package before merging this.

**Comment by johnbelamaric** [comment]
Other PR has merged and I tagged those packages.

/hold cancel

**Comment by johnbelamaric** [comment]
@vjayaramrh @electrocucaracha @henderiw I think this one is the last one that has to merge for the e2e README to work.

**Comment by electrocucaracha** [comment]
The e2e check is giving false positives, I'll try to test it locally until the fix is merged, but I think it is ok to approve it

/lgtm

**Comment by vishwanathj** [comment]
> @vjayaramrh @electrocucaracha @henderiw I think this one is the last one that has to merge for the e2e README to work.

Will take a look and try it out

**Pull request merged**
