### PR TITLE
Fix molecule test python dependencies

### PR DESCRIPTION
**Pull request by electrocucaracha**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Molecule plugins binary has been released, so using the repository is not needed anymore

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Use a fresh new `tox` environment to validate the installation of dependencies. 

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@johnbelamaric @vjayaramrh [this](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/171/e2e/1689748068368388096#1:build-log.txt%3A62568) is another test scenario for hardening the code. Basically, the `smf_pkg_rev` variable is not [populated](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/009.sh#L76)

**Review by vjayaramrh — APPROVED** [review]
/lgtm

**Pull request merged**
