### PR TITLE
Add gce_init.sh startup script and revise instructions

### PR DESCRIPTION
**Pull request by johnbelamaric**
Added a startup script, so the user can launch Nephio Sandbox in a single gcloud command.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
cc @electrocucaracha @vjayaramrh @radoslawc 

The actual command won't work until the PR merges, because it tries to pull the script from GitHub. If you want to try it, then pull out the PR and run it using `gcloud compute instances create --machine-type e2-standard-8 --boot-disk-size 200GB --image-family=ubuntu-2204-lts --image-project=ubuntu-os-cloud --metadata-from-file=startup-script=./gce_init.sh nephio-r1-e2e`.

**Comment by vjayaramrh** [comment]
> cc @electrocucaracha @vjayaramrh @radoslawc
> 
> The actual command won't work until the PR merges, because it tries to pull the script from GitHub. If you want to try it, then pull out the PR and run it using `gcloud compute instances create --machine-type e2-standard-8 --boot-disk-size 200GB --image-family=ubuntu-2204-lts --image-project=ubuntu-os-cloud --metadata-from-file=startup-script=./gce_init.sh nephio-r1-e2e`.

@johnbelamaric Will review

**Review by vjayaramrh — APPROVED** [review]

**Comment by vjayaramrh** [comment]
Reviewed, looks good, could not test out the script though
/lgtm

**Comment by johnbelamaric** [comment]
Closing in favor of #56.

**Pull request closed without merging**
