### PR TITLE
Enabling building all images in nephio in the same time

### PR DESCRIPTION
**Pull request by radoslawc**
Since there is no mechanism to link/make dependencies in jobs for now, we are going to build every image in 'nephio' every time something changes in repo, also lowered pod mem request

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@radoslawc this means every time a change is merged or every time a PR is open?

**Comment by radoslawc** [comment]
> @radoslawc this means every time a change is merged or every time a PR is open?

every time something's merged

**Pull request merged**
