### PR TITLE
Add a subscriber with curl

### PR DESCRIPTION
**Pull request by johnbelamaric**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@denysaleksandrov This is what I have, but free5gc is returning a 400 and `{"cause":"Illegal Token"}`. Any ideas? I even tried using the JSON I captured directly from Chrome dev console; same thing.

**Comment by denysaleksandrov** [comment]
@johnbelamaric I am not sure why you do `-u admin:free5gc`.
Can you try just with `-H "Token: admin"`

```
/free5gc/webconsole # curl -X GET http://localhost:5000/api/subscriber/imsi-208930000000003/20893 -H "Token: admin"

{"plmnID":"20893","ueId":"imsi-208930000000003","AuthenticationSubscription":{"authenticationMethod":"5G_AKA","permanentKey":{"permanentKeyValue":"8baf473f2f8fd09487cccbd7097c6862","encryptionKey":0,"encryptionAlgorithm":0},"sequenceNumber":"000000000023","authenticationManagementField":"8000","milenage":{"op":{"opValue":"","encryptionKey":0,"encryptionAlgorithm":0}},"opc":{"opcValue":"8e27b6af0e692e750f32667a3b14605d","encryptionKey":0,"encryptionAlgorithm":0}},"AccessAndMobilitySubscriptionData":{"gpsis":["msisdn-0900000000"],"subscribedUeAmbr":{"uplink":"1 Gbps","downlink":"2 Gbps"},"nssai":{"defaultSingleNssais":[{"sst":1,"sd":"010203"},{"sst":1,"sd":"112233"}]}},"SessionManagementSubscriptionData":[{"singleNssai":{"sst":1,"sd":"010203"},"dnnConfigurations":{"internet":{"pduSessionTypes":{"defaultSessionType":"IPV4","allowedSessionTypes":["IPV4"]},"sscModes":{"defaultSscMode":"SSC_MODE_1","allowedSscModes":["SSC_MODE_2","SSC_MODE_3"]},"5gQosProfile":{"5qi":9,"arp":{"priorityLevel":8,"preemptCap":"","preemptVuln":""},"priorityLevel":8},"sessionAmbr":{"uplink":"200 Mbps","downlink":"100 Mbps"}},"internet2":{"pduSessionTypes":{"defaultSessionType":"IPV4","allowedSessionTypes":["IPV4"]},"sscModes":{"defaultSscMode":"SSC_MODE_1","allowedSscModes":["SSC_MODE_2","SSC_MODE_3"]},"5gQosProfile":{"5qi":9,"arp":{"priorityLevel":8,"preemptCap":"","preemptVuln":""},"priorityLevel":8},"sessionAmbr":{"uplink":"200 Mbps","downlink":"100 Mbps"}}}},{"singleNssai":{"sst":1,"sd":"112233"},"dnnConfigurations":{"internet":{"pduSessionTypes":{"defaultSessionType":"IPV4","allowedSessionTypes":["IPV4"]},"sscModes":{"defaultSscMode":"SSC_MODE_1","allowedSscModes":["SSC_MODE_2","SSC_MODE_3"]},"5gQosProfile":{"5qi":9,"arp":{"priorityLevel":8,"preemptCap":"","preemptVuln":""},"priorityLevel":8},"sessionAmbr":{"uplink":"200 Mbps","downlink":"100 Mbps"}},"internet2":{"pduSessionTypes":{"defaultSessionType":"IPV4","allowedSessionTypes":["IPV4"]},"sscModes":{"defaultSscMode":"SSC_MODE_1","allowedSscModes":["SSC_MODE_2","SSC_MODE_3"]},"5gQosProfile":{"5qi":9,"arp":{"priorityLevel":8,"preemptCap":"","preemptVuln":""},"priorityLevel":8},"sessionAmbr":{"uplink":"200 Mbps","downlink":"100 Mbps"}}}}],"SmfSelectionSubscriptionData":{"subscribedSnssaiInfos":{"01010203":{"dnnInfos":[{"dnn":"internet"},{"dnn":"internet2"}]},"01112233":{"dnnInfos":[{"dnn":"internet"},{"dnn":"internet2"}]}}},"AmPolicyData":{"subscCats":["free5gc"]},"SmPolicyData":{"smPolicySnssaiData":{"01010203":{"snssai":{"sst":1,"sd":"010203"},"smPolicyDnnData":{"internet":{"dnn":"internet"},"internet2":{"dnn":"internet2"}}},"01112233":{"snssai":{"sst":1,"sd":"112233"},"smPolicyDnnData":{"internet":{"dnn":"internet"},"internet2":{"dnn":"internet2"}}}}},"FlowRules":null}/free5gc/webconsole #
```

**Comment by johnbelamaric** [comment]
> Can you try just with `-H "Token: admin"`?

That worked! Thanks. So, they don't actually have a password, it seems...

The login screen says to use admin/free5gc that's why I did that.

**Comment by electrocucaracha** [comment]
We can fix the ping process later

/lgtm

**Pull request merged**
