### PR TITLE
Remove porch functions from integration

### PR DESCRIPTION
**Pull request by efiacor**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:
Remove porch functions from integration testing
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kispaljr** [comment]
should "packages" be also removed?

**Comment by efiacor** [comment]
> should "packages" be also removed?

Pretty sure not for the time being:

`ubuntu@vm-nephio-ts-fiach-01:~$ kubectl api-resources | grep kpt
packagerevs                                      config.porch.kpt.dev/v1alpha1             true         PackageRev
packagevariants                                  config.porch.kpt.dev/v1alpha1             true         PackageVariant
packagevariantsets                               config.porch.kpt.dev/v1alpha2             true         PackageVariantSet
repositories                                     config.porch.kpt.dev/v1alpha1             true         Repository
resourcegroups                                   kpt.dev/v1alpha1                          true         ResourceGroup
packagerevisionresources                         porch.kpt.dev/v1alpha1                    true         PackageRevisionResources
packagerevisions                                 porch.kpt.dev/v1alpha1                    true         PackageRevision
packages                                         porch.kpt.dev/v1alpha1                    true         PorchPackage
`

**Review by liamfallon — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
