### PR TITLE
Fix ANSIBLE_CMD_EXTRA_VAR_LIST environment variable

### PR DESCRIPTION
**Pull request by electrocucaracha**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR fixes the usage of the ANSIBLE_CMD_EXTRA_VAR_LIST, from an iteration of a comma separated values to a single string. It includes additional improvements to control the e2e behavior. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Use a ANSIBLE_CMD_EXTRA_VAR_LIST string value

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by electrocucaracha** [comment]
The failure reported was related to flakiness in `009.sh`

/override e2e-ubuntu-focal

**Comment by electrocucaracha** [comment]
@lapentad I have included the suggestion that you made on this PR, could you confirm that this version works for you?

**Review by lapentad — APPROVED** [review]
> @lapentad I have included the suggestion that you made on this PR, could you confirm that this version works for you?

@electrocucaracha Works nicely here on Openstack!

One note is that my cluster comes pre-provisioned, and I already have /usr/local/bin/kubectl so I backup it and remove it, so that the ansible script can install it's own and add the symlink (I don't think we need to add this step, it depends on the setup), otherwise it fails linking /usr/local/bin/kubectl to /usr/local/bin/kubectl-v1.27.3

**Comment by electrocucaracha** [comment]
> > @lapentad I have included the suggestion that you made on this PR, could you confirm that this version works for you?
> 
> /approve
> 
> @electrocucaracha Works nicely here on Openstack!
> 
> One note is that my cluster comes pre-provisioned, and I already have /usr/local/bin/kubectl so I backup it and remove it, so that the ansible script can install it's own and add the symlink (I don't think we need to add this step, it depends on the setup), otherwise it fails linking /usr/local/bin/kubectl to /usr/local/bin/kubectl-v1.27.3

Interesting, maybe we can add some logic to determine if the [kubectl role](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/cluster.yml#L86-L88) needs to executed

**Review by vjayaramrh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
