### PR TITLE
Upgrade gtp5G kernel module

### PR DESCRIPTION
**Pull request by electrocucaracha**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
This release version include some bug fixes and improvements

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by vjayaramrh** [comment]
Curious as to how this new version of the kernel module would benefit the nephio project at this time, Thanks.
I did look at the release log at https://github.com/free5gc/gtp5g/compare/v0.8.1...v0.8.2 and trying to understand if there are any specific impacts to the nephio project( e.g would e2e tests improve with this latest update)

**Comment by electrocucaracha** [comment]
> Curious as to how this new version of the kernel module would benefit the nephio project at this time, Thanks. I did look at the release log at [free5gc/gtp5g@v0.8.1...v0.8.2](https://github.com/free5gc/gtp5g/compare/v0.8.1...v0.8.2) and trying to understand if there are any specific impacts to the nephio project( e.g would e2e tests improve with this latest update)

I'm trying to minimize the number of cases for not bringing the `ueransim` tunnel up, but maybe I'm looking at the wrong place, given this task is performed by the [ueransim-ue container](https://github.com/nephio-project/nephio-example-packages/blob/v1.0.1/ueransim/ue/ue-deployment.yaml#L22) which [uses](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/docker/ueransim/ueransim-base/Dockerfile#L14-L15) the UERANSIM project.

I've included an instruction to display logs, hopefully we can catch some of [these error messages](https://github.com/aligungr/UERANSIM/blob/v3.2.6/src/ue/app/task.cpp#L186).

BTW, the difference needs to be [free5gc/gtp5g@v0.8.1...v0.8.2](https://github.com/free5gc/gtp5g/compare/v0.6.8...v0.8.2)

**Pull request merged**
