### PR TITLE
Updating the location of files

### PR DESCRIPTION
**Pull request by arora-sagar**
/kind cleanup

**What this PR does / why we need it**:

- Moving yaml definitions from script to yaml files
- Adding connectivity testing script

**Special notes for your reviewer**:
Updated the scripts to keep the yaml files out of the script. 

**Does this PR introduce a user-facing change?**:
NO

### CODE REVIEW

**Review by efiacor — COMMENTED** [review]
Minor comment.
I understand the logic for naming the .sh files incrementaly for test execution purposes but to me it's not very intuitive as to what each one is doing without opening the file.
For the yaml files I think it would be good to keep the suffix of what it contains rather than 003.yaml etc.

**Comment by arora-sagar** [comment]
> Minor comment. I understand the logic for naming the .sh files incrementaly for test execution purposes but to me it's not very intuitive as to what each one is doing without opening the file. For the yaml files I think it would be good to keep the suffix of what it contains rather than 003.yaml etc.


I agree I just used the approach of R1. For yaml files I can change the name

```bash
002.yaml --> 002-database.yaml and 002-operators.yaml
003.yaml --> 003-core-network.yaml
004.yaml --> 004-ran-network.yaml
```

For test scripts, I can change to

```
001.sh --> 001-infra.sh
002.sh --> 002-dependency.sh
003.sh --> 003-core-network.sh
004.sh --> 004-ran-network.sh
005.sh --> 005-ue.sh
006.sh --> 006-end-to-end-call.sh
```

What do you think @efiacor

**Comment by liamfallon** [comment]
> > Minor comment. I understand the logic for naming the .sh files incrementaly for test execution purposes but to me it's not very intuitive as to what each one is doing without opening the file. For the yaml files I think it would be good to keep the suffix of what it contains rather than 003.yaml etc.
> 
> I agree I just used the approach of R1. For yaml files I can change the name
> 
> ```shell
> 002.yaml --> 002-database.yaml and 002-operators.yaml
> 003.yaml --> 003-core-network.yaml
> 004.yaml --> 004-ran-network.yaml
> ```
> 
> For test scripts, I can change to
> 
> ```
> 001.sh --> 001-infra.sh
> 002.sh --> 002-dependency.sh
> 003.sh --> 003-core-network.sh
> 004.sh --> 004-ran-network.sh
> 005.sh --> 005-ue.sh
> 006.sh --> 006-end-to-end-call.sh
> ```
> 
> What do you think @efiacor ? Though I need @electrocucaracha approval too



> > Minor comment. I understand the logic for naming the .sh files incrementaly for test execution purposes but to me it's not very intuitive as to what each one is doing without opening the file. For the yaml files I think it would be good to keep the suffix of what it contains rather than 003.yaml etc.
> 
> I agree I just used the approach of R1. For yaml files I can change the name
> 
> ```shell
> 002.yaml --> 002-database.yaml and 002-operators.yaml
> 003.yaml --> 003-core-network.yaml
> 004.yaml --> 004-ran-network.yaml
> ```
> 
> For test scripts, I can change to
> 
> ```
> 001.sh --> 001-infra.sh
> 002.sh --> 002-dependency.sh
> 003.sh --> 003-core-network.sh
> 004.sh --> 004-ran-network.sh
> 005.sh --> 005-ue.sh
> 006.sh --> 006-end-to-end-call.sh
> ```
> 
> What do you think @efiacor ? Though I need @electrocucaracha approval too

I agree with this proposal Sagar. I think this is better.

**Comment by electrocucaracha** [comment]
I like the idea to provide some hint thru the file names, let's rename those files to something that make more sense

**Comment by efiacor** [comment]
> > Minor comment. I understand the logic for naming the .sh files incrementaly for test execution purposes but to me it's not very intuitive as to what each one is doing without opening the file. For the yaml files I think it would be good to keep the suffix of what it contains rather than 003.yaml etc.
> 
> I agree I just used the approach of R1. For yaml files I can change the name
> 
> ```shell
> 002.yaml --> 002-database.yaml and 002-operators.yaml
> 003.yaml --> 003-core-network.yaml
> 004.yaml --> 004-ran-network.yaml
> ```
> 
> For test scripts, I can change to
> 
> ```
> 001.sh --> 001-infra.sh
> 002.sh --> 002-dependency.sh
> 003.sh --> 003-core-network.sh
> 004.sh --> 004-ran-network.sh
> 005.sh --> 005-ue.sh
> 006.sh --> 006-end-to-end-call.sh
> ```
> 
> What do you think @efiacor ? Though I need @electrocucaracha approval too

Perfect. Thank you sir.

**Comment by electrocucaracha** [comment]
@arora-sagar I have seen [this issue](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/231/e2e-oai-ubuntu-jammy/1750560988890927104#1:build-log.txt%3A411) frequently in Ubuntu Jammy images, where the official Ubuntu repository is locked. We can create in R3+ our private repo to mitigate these dependencies.

**Comment by arora-sagar** [comment]
Do you see this in focal too? Probably we can move to focal for R2. Best Regards,Sagar AroraOn 25 Jan 2024, at 18:01, Victor Morales ***@***.***> wrote:﻿
@arora-sagar I have seen this issue frequently in Ubuntu Jammy images, where the official Ubuntu repository is locked. We can create in R3+ our private repo to mitigate these dependencies.

**Comment by electrocucaracha** [comment]
> Do you see this in focal too? Probably we can move to focal for R2. Best Regards,Sagar Arora

No too often, that's another possibility.

**Comment by electrocucaracha** [comment]
These changes don't have any related change to `free5gc` so we can ignore the issues.

/override e2e-free5gc-fedora-34
/override e2e-free5gc-ubuntu-focal

**Comment by electrocucaracha** [comment]
Give a second try to OAI End-to-End test execution

/test e2e-oai-ubuntu-jammy

**Comment by electrocucaracha** [comment]
This seems to be a timeout issue with is already addressed on #230
 
/override e2e-oai-ubuntu-jammy
/lgtm
/approve

**Pull request merged**
