### PR TITLE
Add kpt ansible module

### PR DESCRIPTION
**Pull request by electrocucaracha**
Wrapping the kpt client commands in to an ansible module can provide a better control on the output and avoid false positives during the execution. This change introduces the kpt ansible module.

### CODE REVIEW

**Review by rravindran123 — COMMENTED** [review]
ran the playbooks in gcp VM, looks ok.

**Comment by vishwanathj** [comment]
@electrocucaracha Can we have a discussion around this PR if it is a must have for R1 before this gets merged, Thanks

**Comment by vjayaramrh** [comment]
@electrocucaracha I pulled this PR and executed `tox -e kpt` and see the below snippet at the end. Is this how I am supposed to test this PR?

```
PLAY [Destroy] *****************************************************************

TASK [Destroy molecule instance(s)] ********************************************
changed: [localhost]

TASK [Populate instance config] ************************************************
ok: [localhost]

TASK [Dump instance config] ****************************************************
--- before: /home/openshift/.cache/molecule/kpt/default/instance_config.yml
+++ after: /home/openshift/.ansible/tmp/ansible-local-88794ezi76we/tmp0lwpqgm7
@@ -1,2 +1,2 @@
-- {address: 192.168.122.244, identity_file: /home/openshift/.cache/molecule/kpt/default/.vagrant/machines/bionic/libvirt/private_key,
-  instance: bionic, port: '22', user: vagrant}
+# Molecule managed
+{}

changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

INFO     Pruning extra files from scenario ephemeral directory
_________________________________________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________________________________________
  kpt: commands succeeded
  congratulations :)

```

**Comment by electrocucaracha** [comment]
> @electrocucaracha I pulled this PR and executed `tox -e kpt` and see the below snippet at the end. Is this how I am supposed to test this PR?

Yes, we have to do those integration tests manually until we include something into the CI.

**Review by vjayaramrh — APPROVED** [review]

**Pull request merged**
